spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka 